
-- t_datasource
INSERT INTO `t_datasource`(`id`,`name`,`description`,`type`,`address`,`username`,`password`,`contacts`,`properties`,`is_delete`,`ctime`,`mtime`) VALUES (2, 'java prometheus', 'jvm&qps', 2, 'http://10.32.3.238:10902', '0', '0', '0', '', 1, NOW(), NOW());
INSERT INTO `t_datasource`(`id`,`name`,`description`,`type`,`address`,`username`,`password`,`contacts`,`properties`,`is_delete`,`ctime`,`mtime`) VALUES (3, '运维指标prometheus', '容器指标', 2, 'http://10.131.3.1:33333', '', '', '', '', 0, NOW(), NOW());

--t_alarm_metric
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (7, '近一分钟内负载', 'system_load_average_1m{application=\"${appCode}\"}', 1, '近一分钟内负载', 2, 'INIT,JAVA,AOS', 1, 0, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (8, 'CPU 使用率', 'system_cpu_usage{application=\"${appCode}\"}', 1, 'CPU 使用率', 2, 'INIT,JAVA,AOS', 1, 0, 1, 3, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (9, '服务QPS', 'sum(rate(http_server_requests_seconds_count{application=\"${appCode}\",uri!~\"/actuator.*\",uri!=\"/\"}[1m]))', 1, '服务QPS', 2, 'INIT,JAVA,AOS', 2, 0, 1, 0, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (14, 'JVM 堆内存已用', 'jvm_memory_used_bytes{application=\"${appCode}\", area=\"heap\"}', 1, 'JVM 堆内存已用', 2, 'INIT,JAVA,AOS', 1, 2, 1, 1, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (17, 'HTTP 500错误', 'http_server_requests_seconds_count{status=\"500\",application=\"${appCode}\"}', 1, 'HTTP 500错误', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (18, 'JVM活动线程数', 'jvm_threads_live{application=\"${appCode}\"} or jvm_threads_live_threads{application=\"${appCode}\"}', 1, '活动线程数', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (20, 'JVM Full GC', 'jvm_gc_pause_seconds_count{application=\"${appCode}\",action=\"Metadata GC Threshold\"}', 1, 'JVM Full GC', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (21, 'JVM Major GC', 'jvm_gc_pause_seconds_count{action=\"end of major GC\",application=\"${appCode}\"}', 1, 'JVM Major GC', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (24, 'JVM守护线程数', 'jvm_threads_daemon{application=\"${appCode}\"} or jvm_threads_daemon_threads{application=\"${appCode}\"}', 1, 'JVM守护线程数', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (25, '状态线程数量', 'jvm_threads_states_threads{application=\"${appCode}\",state=\"${threadState}\"}', 1, '状态线程数量', 2, 'JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (26, '单一接口QPS', 'sum(rate(http_server_requests_seconds_count{application=\"${appCode}\",uri=\"${uri}\"}[1m])) by (instance)', 1, '单一接口QPS', 2, 'AOS', 2, 0, 1, 0, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (27, '单一接口最大响应时间', 'http_server_requests_seconds_max{application=\"${appCode}\",uri=\"${uri}\"}', 1, '单一接口最大响应时间{appCode},{uri}', 2, 'AOS', 2, 0, 1, 5, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (28, '单一接口平均响应时间', 'sum(delta(http_server_requests_seconds_sum{application=\"${appCode}\",uri=\"${uri}\"}[1m])) / sum(delta(http_server_requests_seconds_count{application=\"${appCode}\",uri=\"${uri}\"}[1m]))', 1, '单一接口平均响应时间 {appCode},{uri}', 2, 'AOS', 2, 0, 1, 5, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (29, 'JVM非堆内存', 'jvm_memory_used_bytes{application=\"${appCode}\", area=\"nonheap\"}', 1, 'jvm非堆内存', 2, 'INIT,JAVA,AOS', 1, 2, 1, 1, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (30, 'JVM内存', 'jvm_memory_used_bytes{application=\"${appCode}\"}', 1, 'jvm内存', 2, 'INIT,JAVA,AOS', 1, 2, 1, 1, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (31, 'JVM堆内存使用占比', '(sum(jvm_memory_used_bytes{application=\"${appCode}\",area=\"heap\"}) by (instance))*100/(sum(jvm_memory_max_bytes{application=\"${appCode}\", area=\"heap\"}) by (instance))', 1, 'jvm堆内存使用占比', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (32, 'JVM 非堆使用占比', '(sum(jvm_memory_used_bytes{application=\"${appCode}\",area=\"nonheap\"}) by (instance))*100/(sum(jvm_memory_max_bytes{application=\"${appCode}\", area=\"nonheap\"}) by (instance))', 1, 'jvm non-heap使用占比', 2, 'INIT,JAVA,AOS', 1, 2, 1, 0, '', '', '{\"metric_field_key\":\"instance\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (33, '容器应用资源启动百分比', ' (kube_deployment_status_replicas_available{biz_application=\"${appCode}\"} / kube_deployment_spec_replicas{biz_application=\"${appCode}\"}) * 100 ', 1, '容器应用资源启动百分比', 2, 'INIT,AOS', 4, 0, 1, 3, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (34, '容器实例近3m内实例重启次数', 'changes(kube_pod_container_status_restarts_total{job!=\"\",biz_application=\"${appCode}\"}[3m])', 3, '容器实例近3m内实例有重启次数', 2, 'INIT,AOS', 4, 0, 1, 0, '', '', '{\"metric_field_key\":\"pod\",\"namespace\":\"namespace\",\"pod\":\"pod\",\"container\":\"container\"}', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (35, '容器实例近1m内读IOPS', 'round((rate(container_fs_reads_total{image!=\"\",biz_application=\"${appCode}\"}[1m]) or irate(container_fs_reads_total{image!=\"\",biz_application=\"${appCode}\"}[1m])))', 1, '容器实例近1m内读IOPS', 2, 'INIT,AOS', 4, 0, 1, 0, '', '', '', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (36, '容器实例未运行', ' kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\",biz_application=\"${appCode}\"} ', 1, '容器实例未运行', 2, 'INIT,AOS', 4, 0, 1, 0, ' ', ' ', ' ', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (37, '容器实例近1m OOM', 'changes(kube_pod_container_status_terminated_reason{reason=\"OOMKilled\",biz_application=\"${appCode}\"}[1m]) ', 1, '容器实例 OOM', 2, 'INIT,AOS', 4, 0, 1, 0, ' ', ' ', ' ', 0, NOW(), NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (38, '容器实例近1m内接收流量', 'round((((rate(container_network_receive_bytes_total {interface=\"eth0\",name!=\"\",biz_application=\"${appCode}\"}[1m]))) / 1024 / 1024 * 8)) ', 1, '容器实例近1m内接收流量', 2, 'INIT,AOS', 4, 0, 1, 1, '', '', '', 0, NOW(),NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (39, '容器实例近1m发送流量', 'round((((rate(container_network_transmit_bytes_total{interface=\"eth0\",name!=\"\",biz_application=\"${appCode}\"}[1m])))/ 1024 / 1024 * 8)) ', 1, '容器实例近1m发送流量', 2, 'INIT,AOS', 4, 0, 1, 1, '', '', '', 0, NOW(),NOW());
INSERT INTO `t_alarm_metric`(`id`,`name`,`expression`,`time_window`,`description`,`source_type`,`metric_tag`,`metric_type`,`group_type`,`collect_type`,`metric_unit`,`composite_metric_expression`,`formula`,`ext_data`,`is_delete`,`ctime`,`mtime`) VALUES (40, '容器实例近3m容器CPU 使用率', 'rate(container_cpu_usage_seconds_total{biz_application=\"${appCode}\"}[3m])', 3, '容器实例近3m容器CPU 使用率', 2, 'INIT,AOS', 4, 0, 1, 3, '', '', '', 0, NOW(), NOW());

--t_alarm_level
INSERT INTO `t_alarm_level` (`id`,`level`,`alarm_channels`,`alarm_scope`,`alarm_rate`,`is_delete`,`ctime`,`mtime`) VALUES (1,'P0','1,2,3','1,2','{\"rateType\":2,\"rateInterval\":1,\"rateTimes\":20}',0, NOW(), NOW());
INSERT INTO `t_alarm_level` (`id`,`level`,`alarm_channels`,`alarm_scope`,`alarm_rate`,`is_delete`,`ctime`,`mtime`) VALUES (2,'P1','1,3','1,2','{\"rateType\":2,\"rateInterval\":3,\"rateTimes\":20}',0, NOW(), NOW());
INSERT INTO `t_alarm_level` (`id`,`level`,`alarm_channels`,`alarm_scope`,`alarm_rate`,`is_delete`,`ctime`,`mtime`) VALUES (3,'P2','1,3','1,2','{\"rateType\":2,\"rateInterval\":3,\"rateTimes\":10}',0, NOW(), NOW());
INSERT INTO `t_alarm_level` (`id`,`level`,`alarm_channels`,`alarm_scope`,`alarm_rate`,`is_delete`,`ctime`,`mtime`) VALUES (4,'P3','3','1','{\"rateType\":3,\"rateInterval\":0,\"rateTimes\":0}',0, NOW(), NOW());
INSERT INTO `t_alarm_level` (`id`,`level`,`alarm_channels`,`alarm_scope`,`alarm_rate`,`is_delete`,`ctime`,`mtime`) VALUES (5,'P4','3','1','{\"rateType\":1,\"rateInterval\":0,\"rateTimes\":1}',0, NOW(), NOW());
